### ISSUE TITLE
refusing to connect

### ISSUE THREAD

**Issue by satyamedh** [minecraft-dev/mcdev.io#24]
the website is refusing to connect

**Comment by satyamedh** [comment]
@DenWav hello, is this getting fixed anytime soon? I heavily rely on this plugin, since it's been broken I haven't been able to start my new project?!?!??!?!

**Comment by DenWav** [comment]
The website is fine. You'll need to provide more information.

**Comment by satyamedh** [comment]
@DenWav 
![Screenshot_20210924_012133](https://user-images.githubusercontent.com/47636284/134574657-00494605-0826-4950-9863-64f26f7d6f4f.png)

**Comment by RedNesto** [comment]
![image](https://user-images.githubusercontent.com/13600250/134579140-01670ad9-6c4a-45fb-a11a-f643280b4b87.png)

**Comment by RedNesto** [comment]
What's surprising is that even the github fallback doesn't work for some users., which makes me think this more a firewall/isp (or cloudflare ?) issue.

**Comment by satyamedh** [comment]
I can access the github fallback easily, why can't intellij?

**Comment by satyamedh** [comment]
AFAIK @RedNesto it's connecting to the IP of domain without problems, then it comes to the little iframe which points to the actual site, my PC tries to connect to it, waits a long time for some google adservices to load and then ends up saying the connection took too long.

when I originally made this issue it would just refuse to connect altogether

**Comment by RedNesto** [comment]
> I can access the github fallback easily, why can't intellij?

We don't know, this is why we can't fix it. Same for the iframe problem you mentioned.

**Comment by satyamedh** [comment]
@RedNesto can I help?

**Comment by satyamedh** [comment]
my discord is Satyamedh#2579 if you need any more diagnostic information, please shoot me a DM!

**Comment by RedNesto** [comment]
Unfortunately I don't know enough about how the website is hosted and configured to be able to help fixing or working around this issue.

**Comment by satyamedh** [comment]
okay, I guess I'll wait for an official respose then

**Comment by satyamedh** [comment]
my apologies for being such a kid
